#!/usr/bin/env bash
# ... 
sudo su
apt update
apt install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/\(server_name _;\)/\1\nrewrite ^\/redirect_me https\:\/\/google\.com\/ permanent;/" /etc/nginx/sites-available/default
service nginx restart