#!/usr/bin/env bash
#echo "give me a bottle of rum!"

function sTerm()
{
    echo "I hate the kill command"
    shadowrealm
}

function shadowrealm()
{
    rm /var/run/myscript.pid
    exit
}

function huh()
{
    echo "Y U no love me?!"
}

trap sTerm SIGTERM
trap shadowrealm SIGQUIT
trap huh SIGINT

cat > /var/run/myscript.pid <<eof
$$
eof

while true
do
    echo "To infinity and beyond"
    sleep 2
done