#!/usr/bin/env bash
#echo "give me a bottle of rum!"


hr=1
min=1 
echo "Hour:" $hr 

while [ $hr -lt 13 ] 
do
    
    echo $min 
    min=$((min+1))    
    
    
        if  [ $min == 60 -a $hr -le 12 ] ;then
            min=1 
            hr=$((hr+1)) 
            if [ $hr != 13 ]
            then 
              echo "Hour:" $hr 
            fi
        fi
        
        
    
done