#!/usr/bin/env bash
#echo "give me a bottle of rum!"

list=$(ls) 
#list=$( grep -Eo "[^-].*" <<< "$(grep -Eo "[^0-9a-zA-Z].*" <<< "$list")" )

for li in $list
do
    #tmp=$( grep -Eo "[^-].*" <<< "$(grep -Eo "[^0-9a-zA-Z].*" <<< "$li")" )
    tmp=$( grep -Poe "[0-9a-zA-Z]*-\K(.*)" <<< "$li")
    echo "$tmp"
done