#!/usr/bin/env bash
#this is comm
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default 
pkill apache2
sudo chmod 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
