#!/usr/bin/env bash
#this is comm
sudo service nginx stop
sudo sed -i "2i user nginx nginx;" /etc/nginx/nginx.conf
sudo sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-enabled/default 
sudo chown -R nginx:nginx /etc/nginx
sudo -u nginx chmod 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx start

