#!/usr/bin/env bash
#this is comm
sudo sed -i "2i user nginx nginx;" /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /etc/nginx
sudo -u nginx chmod 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx start

